---
#
# main entry point for the ansible playbook. We include the package.yml based on the
# switch in the /defaults/main.yml
#
- include: supervisor.yml
  when: supervisor_enabled
  tags: [supervisor]
